export enum ClickErrorCode {
  SUCCESS = 0,
  SIGN_CHECK_FAILED = -1,
  INVALID_AMOUNT = -2,
  ACTION_NOT_FOUND = -3,
  ALREADY_PAID = -4,
  ORDER_NOT_FOUND = -5,
  TRANSACTION_DOES_NOT_EXIST = -6,
  FAILED_TO_UPDATE_ORDER = -7,
  ERROR_IN_REQUEST_FROM_CLICK = -8,
  TRANSACTION_CANCELLED = -9,
}
